name: Bug report
description: 反馈问题
labels: bug
body:
- type: input
  id: issue_link
  attributes:
    label: "可复现的链接（包含复现链接与示例代码）："
    description: "一个最小化的重现示例能让我们精确地定位问题，从而快速解决问题。"
  validations:
    required: true
- type: textarea
  id: issue_describe
  attributes:
    label: "问题描述与截图："
  validations:
    required: true
- type: markdown
  attributes:
    value: "在发布问题之前，请先查阅[最新文档](https://vxetable.cn/)确保使用的是最新版本，并仔细阅读所填写的步骤，以确保是详细和清晰的。"
- type: input
  id: issue_expect
  attributes:
    label: "期望的结果："
- type: input
  id: issue_os_version
  attributes:
    label: "操作系统："
    placeholder: "例如：window10"
  validations:
    required: true
- type: input
  id: issue_browser_version
  attributes:
    label: "浏览器版本："
    placeholder: "例如：chrome 95.0.4638.69"
  validations:
    required: true
- type: input
  id: issue_vue_version
  attributes:
    label: "vue 版本："
    placeholder: "例如：3.4.27"
  validations:
    required: true
- type: input
  id: issue_vxe_ui_version
  attributes:
    label: "vxe-pc-ui 版本："
    placeholder: "例如：4.2.2"
  validations:
    required: true
- type: input
  id: issue_vxe_table_version
  attributes:
    label: "vxe-table 版本："
    placeholder: "例如：4.7.81"
  validations:
    required: true
- type: checkboxes
  id: issue_confirm_latest_version
  attributes:
    label: "是否使用当前最新版本？"
    description: "官方只维护最新版本，如果不是最新版本，请先更新到[最新版本](https://vxetable.cn/)之后再提！"
    options:
    - label: "我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。"
      required: true