// 按需加载依赖

// object
export * from 'xe-utils/methods/object/assign'
export * from 'xe-utils/methods/object/objectEach'
// export * from 'xe-utils/methods/object/lastObjectEach'
export * from 'xe-utils/methods/object/objectMap'

// array
export * from 'xe-utils/methods/array/map'
export * from 'xe-utils/methods/array/some'
// export * from 'xe-utils/methods/array/every'
export * from 'xe-utils/methods/array/includeArrays'
export * from 'xe-utils/methods/array/arrayEach'
// export * from 'xe-utils/methods/array/lastArrayEach'
// export * from 'xe-utils/methods/array/uniq'
// export * from 'xe-utils/methods/array/union'
// export * from 'xe-utils/methods/array/toArray'
export * from 'xe-utils/methods/array/sortBy'
// export * from 'xe-utils/methods/array/shuffle'
// export * from 'xe-utils/methods/array/sample'
export * from 'xe-utils/methods/array/slice'
export * from 'xe-utils/methods/array/filter'
// export * from 'xe-utils/methods/array/findKey'
// export * from 'xe-utils/methods/array/includes'
export * from 'xe-utils/methods/array/find'
export * from 'xe-utils/methods/array/findLast'
// export * from 'xe-utils/methods/array/reduce'
// export * from 'xe-utils/methods/array/copyWithin'
// export * from 'xe-utils/methods/array/chunk'
// export * from 'xe-utils/methods/array/zip'
// export * from 'xe-utils/methods/array/unzip'
// export * from 'xe-utils/methods/array/zipObject'
// export * from 'xe-utils/methods/array/pluck'
// export * from 'xe-utils/methods/array/invoke'
export * from 'xe-utils/methods/array/toArrayTree'
export * from 'xe-utils/methods/array/toTreeArray'
export * from 'xe-utils/methods/array/findTree'
export * from 'xe-utils/methods/array/eachTree'
export * from 'xe-utils/methods/array/mapTree'
export * from 'xe-utils/methods/array/filterTree'
export * from 'xe-utils/methods/array/searchTree'
// export * from 'xe-utils/methods/array/arrayIndexOf'
// export * from 'xe-utils/methods/array/arrayLastIndexOf'

// base
// import hasOwnProp from 'xe-utils/methods/base/hasOwnProp'
export * from 'xe-utils/methods/base/isArray'
export * from 'xe-utils/methods/base/isNull'
// export * from 'xe-utils/methods/base/isNaN'
export * from 'xe-utils/methods/base/isUndefined'
export * from 'xe-utils/methods/base/isFunction'
export * from 'xe-utils/methods/base/isObject'
export * from 'xe-utils/methods/base/isString'
export * from 'xe-utils/methods/base/isPlainObject'
// export * from 'xe-utils/methods/base/isLeapYear'
export * from 'xe-utils/methods/base/isDate'
export * from 'xe-utils/methods/base/eqNull'
export * from 'xe-utils/methods/base/each'
// export * from 'xe-utils/methods/base/forOf'
// export * from 'xe-utils/methods/base/lastForOf'
export * from 'xe-utils/methods/base/indexOf'
// export * from 'xe-utils/methods/base/lastIndexOf'
// export * from 'xe-utils/methods/base/keys'
// export * from 'xe-utils/methods/base/values'
export * from 'xe-utils/methods/base/clone'
export * from 'xe-utils/methods/base/getSize'
// export * from 'xe-utils/methods/base/lastEach'
export * from 'xe-utils/methods/base/remove'
export * from 'xe-utils/methods/base/clear'
// export * from 'xe-utils/methods/base/isFinite'
// export * from 'xe-utils/methods/base/isFloat'
// export * from 'xe-utils/methods/base/isInteger'
export * from 'xe-utils/methods/base/isBoolean'
export * from 'xe-utils/methods/base/isNumber'
export * from 'xe-utils/methods/base/isRegExp'
export * from 'xe-utils/methods/base/isError'
// export * from 'xe-utils/methods/base/isTypeError'
export * from 'xe-utils/methods/base/isEmpty'
// iexport * from 'xe-utils/methods/base/isSymbol'
// export * from 'xe-utils/methods/base/isArguments'
// export * from 'xe-utils/methods/base/isElement'
// export * from 'xe-utils/methods/base/isDocument'
// export * from 'xe-utils/methods/base/isWindow'
// export * from 'xe-utils/methods/base/isFormData'
// export * from 'xe-utils/methods/base/isMap'
// export * from 'xe-utils/methods/base/isWeakMap'
// export * from 'xe-utils/methods/base/isSet'
// export * from 'xe-utils/methods/base/isWeakSet'
// export * from 'xe-utils/methods/base/isMatch'
export * from 'xe-utils/methods/base/isEqual'
export * from 'xe-utils/methods/base/isEqualWith'
// export * from 'xe-utils/methods/base/getType'
export * from 'xe-utils/methods/base/uniqueId'
export * from 'xe-utils/methods/base/findIndexOf'
// export * from 'xe-utils/methods/base/findLastIndexOf'
export * from 'xe-utils/methods/base/toStringJSON'
export * from 'xe-utils/methods/base/toJSONString'
// export * from 'xe-utils/methods/base/entries'
// export * from 'xe-utils/methods/base/pick'
// export * from 'xe-utils/methods/base/omit'
// export * from 'xe-utils/methods/base/first'
// export * from 'xe-utils/methods/base/last'
export * from 'xe-utils/methods/base/has'
export * from 'xe-utils/methods/base/get'
export * from 'xe-utils/methods/base/set'
// export * from 'xe-utils/methods/base/groupBy'
// export * from 'xe-utils/methods/base/countBy'
// export * from 'xe-utils/methods/base/range'
export * from 'xe-utils/methods/base/destructuring'

// number
// export * from 'xe-utils/methods/number/random'
// export * from 'xe-utils/methods/number/max'
// export * from 'xe-utils/methods/number/min'
// export * from 'xe-utils/methods/number/commafy'
export * from 'xe-utils/methods/number/round'
export * from 'xe-utils/methods/number/ceil'
export * from 'xe-utils/methods/number/floor'
export * from 'xe-utils/methods/number/toFixed'
export * from 'xe-utils/methods/number/toFixedString'
export * from 'xe-utils/methods/number/toFixedNumber'
export * from 'xe-utils/methods/number/toInteger'
export * from 'xe-utils/methods/number/toNumber'
export * from 'xe-utils/methods/number/add'
export * from 'xe-utils/methods/number/subtract'
// export * from 'xe-utils/methods/number/multiply'
// export * from 'xe-utils/methods/number/divide'
// export * from 'xe-utils/methods/number/sum'
// export * from 'xe-utils/methods/number/mean'

// date
export * from 'xe-utils/methods/date/getWhatYear'
export * from 'xe-utils/methods/date/getWhatMonth'
export * from 'xe-utils/methods/date/getWhatDay'
export * from 'xe-utils/methods/date/toStringDate'
export * from 'xe-utils/methods/date/toDateString'
// export * 'xe-utils/methods/date/now'
// export * from 'xe-utils/methods/date/timestamp'
export * from 'xe-utils/methods/date/isDateSame'
export * from 'xe-utils/methods/date/getWhatWeek'
// export * from 'xe-utils/methods/date/getYearDay'
export * from 'xe-utils/methods/date/getYearWeek'
// export * from 'xe-utils/methods/date/getMonthWeek'
// export * from 'xe-utils/methods/date/getDayOfYear'
// export * from 'xe-utils/methods/date/getDayOfMonth'
// export * from 'xe-utils/methods/date/getDateDiff'

// string
// export * from 'xe-utils/methods/string/padEnd'
// export * from 'xe-utils/methods/string/padStart'
// export * from 'xe-utils/methods/string/repeat'
// export * from 'xe-utils/methods/string/trim'
// export * from 'xe-utils/methods/string/trimRight'
// export * from 'xe-utils/methods/string/trimLeft'
export * from 'xe-utils/methods/string/escape'
// export * from 'xe-utils/methods/string/unescape'
export * from 'xe-utils/methods/string/camelCase'
// export * from 'xe-utils/methods/string/kebabCase'
// export * from 'xe-utils/methods/string/startsWith'
// export * from 'xe-utils/methods/string/endsWith'
export * from 'xe-utils/methods/string/template'
export * from 'xe-utils/methods/string/toString'

// function
// export * from 'xe-utils/methods/function/property'
// export * from 'xe-utils/methods/function/bind'
// export * from 'xe-utils/methods/function/once'
// export * from 'xe-utils/methods/function/after'
// export * from 'xe-utils/methods/function/before'
export * from 'xe-utils/methods/function/throttle'
export * from 'xe-utils/methods/function/debounce'
// export * from 'xe-utils/methods/function/delay'

// url
// export * from 'xe-utils/methods/url/unserialize'
// export * from 'xe-utils/methods/url/serialize'
// export * from 'xe-utils/methods/url/parseUrl'

// browse
// export * from 'xe-utils/methods/browse/getBaseURL'
// export * from 'xe-utils/methods/browse/locat'
// export * from 'xe-utils/methods/browse/cookie'
export * from 'xe-utils/methods/browse/browse'
